# NumPy
NumPy is a Linear Algebra Library in Python and it is the holy grail and the main building block of Data Science using Python. Almost all the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

It is bound to several C libraries which makes NumPy one of the fastest libraries in Python.

We will learn the basics of NumPy, to get started we need to install it!

## Installation Instructions

**It is highly recommended you install Python using the Anaconda distribution to make sure all underlying dependencies (such as Linear Algebra libraries) all sync up with the use of a conda install. If you don't have Anaconda, install NumPy by going to your terminal or command prompt and type:**
    
    !pip install numpy
    conda install numpy
    


In [1]:
!pip install numpy

## Using NumPy

Once you've installed NumPy you can import it as a library:

In [2]:
import numpy as np

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation.

# Numpy Arrays

Numpy arrays essentially of two types: vectors and matrices. Vectors are strictly 1-D arrays and matrices are 2-D (Note: A matrix can still have only one row or one column).

The following cells explain on creation of NumPy arrays.

## Creating NumPy Arrays

### From a Python List

An array can be created by directly converting a list or list of lists:

In [3]:
import numpy as np

In [4]:
np.array([])

array([], dtype=float64)

In [5]:
arr1 = np.array([])   # create an empty array
print(arr1)
print(type(arr1))

[]
<class 'numpy.ndarray'>


In [6]:
l1=[]
print(type(l1))

<class 'list'>


In [7]:
arr12 = np.array(l1)   # create an empty array
print(arr12)
print(type(arr12))

[]
<class 'numpy.ndarray'>


In [8]:
l1 = [1,2,3,4,5]
print(l1)
print(type(l1))

[1, 2, 3, 4, 5]
<class 'list'>


In [9]:
arr13 = np.array(  [  1,2,3,4,5    ]      )
print(arr13)
print(type(arr13))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [10]:
arr13 = np.array( l1     )
print(arr13)
print(type(arr13))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [11]:
arr2 = np.array([ 1 ,2 ,3, 4, 5])
print(arr1)
print(type(arr1))

[]
<class 'numpy.ndarray'>


In [12]:
my_list = [1,2,3,4,5]
print(my_list)
print(type(my_list))

[1, 2, 3, 4, 5]
<class 'list'>


In [13]:
a=np.array(my_list)

In [14]:
a

array([1, 2, 3, 4, 5])

In [15]:
type(a)

numpy.ndarray

In [16]:
a+2

array([3, 4, 5, 6, 7])

In [17]:
type(my_list)

list

In [18]:
my_list

[1, 2, 3, 4, 5]

In [19]:
my_list+[45]

[1, 2, 3, 4, 5, 45]

In [20]:
type(a) # ndarray is number dimension array

numpy.ndarray

In [21]:
a

array([1, 2, 3, 4, 5])

In [22]:
a.ndim  # number of dimensions in the array

1

In [23]:
a.size  # size of an array is the no. of items

5

In [24]:
a.shape # shape of array

(5,)

In [25]:
t1 = (5,2)
type(t1)

tuple

In [26]:
t2 = (1,5)
type(t2)

tuple

In [27]:
#t3 = (,5)

In [28]:
t4 = (5)
type(t4)

int

In [29]:
t5 = (5,)
type(t5)

tuple

#### Arrays can be of n dimensions.

In [30]:
c = np.array([1,2,3,4,5,6,7,8,9])
print(c)

[1 2 3 4 5 6 7 8 9]


In [31]:
c[3]

4

In [32]:
print(type(c))
print(c.ndim)

<class 'numpy.ndarray'>
1


In [33]:
x = np.array( [
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
]
    
)

In [34]:
print(x)
print("-"*100)
print(type(x))
print("-"*100)
print(x.ndim)
print("-"*100)
print(x.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
----------------------------------------------------------------------------------------------------
<class 'numpy.ndarray'>
----------------------------------------------------------------------------------------------------
2
----------------------------------------------------------------------------------------------------
(3, 4)


In [35]:
x[0][3]

4

In [36]:
b = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(b)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [37]:
my_matrix = [
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
] # list of lists
my_matrix

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [38]:
my_matrix = [
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
] # list of lists
my_matrix

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [39]:
my_matrix = [[1,2,3,4],[5,6,7,8],[9,10,11,12]] # list of lists
my_matrix

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [40]:
my_matrix[1][2]

7

In [41]:
arr2 = np.array(my_matrix)

In [42]:
print(arr2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [43]:
arr = np.array([ [1,2,3],
                [4,5,6],
                [7,8,9]
               ])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
b=np.array(my_matrix) # generates a 2-d array
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [45]:
# Array summary
print('The Dimension of array',b.ndim) # dimensions of given array

The Dimension of array 2


In [46]:
print('The size of array:',b.size) # Number of elements in array

The size of array: 12


In [47]:
print('The datatype of element:',b.dtype) # Datatype of elements in array

The datatype of element: int32


In [48]:
print('The type of structure:',type(b))

The type of structure: <class 'numpy.ndarray'>


In [49]:
print('The shape:',b.shape)

The shape: (3, 4)


In [50]:
b.shape

(3, 4)

In [51]:
(5,)

(5,)

In [52]:
arr1= np.array([
        [1,2,3],
        [4,5,6]
])

print(arr1)
print(arr1.ndim)

[[1 2 3]
 [4 5 6]]
2


In [53]:
arr1= np.array([
    [
        [1,2,3],
        [4,5,6]
    ], 
    
    [
        [7,8,9],
        [10,11,12]
    ]
])
print(arr1)
print(arr1.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3


In [54]:
y = np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9],
        [10,11,12]
    ]
])

In [55]:
print(y)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [56]:
y[0][1][0]

4

In [57]:
print(y)
print("-"*100)
print(type(y))
print("-"*100)
print(y.ndim)
print("-"*100)
print(y.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
----------------------------------------------------------------------------------------------------
<class 'numpy.ndarray'>
----------------------------------------------------------------------------------------------------
3
----------------------------------------------------------------------------------------------------
(2, 2, 3)


In [58]:
y.size

12

In [59]:
arr1= np.array([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]])
arr1

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [60]:
arr1 = np.array([
    [
        [1,2,3],
        [4,5,6]
    ],

    [
        [4,5,4],
        [9,0,9]
    ]
])
print(arr1)

[[[1 2 3]
  [4 5 6]]

 [[4 5 4]
  [9 0 9]]]


In [61]:
arr1[1][1][2]

9

In [62]:
arr1.shape

(2, 2, 3)

In [63]:
arr1.ndim

3

In [64]:
arr1.size

12

In [65]:
arr1[0][1][2]

6

In [66]:
arr2=np.array(["this",'is'])

In [67]:
arr2

array(['this', 'is'], dtype='<U4')

In [68]:
np.mean([1,2,3,45])

12.75

In [69]:
arr2

array(['this', 'is'], dtype='<U4')

In [70]:
np.mean(arr2)

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U4'), dtype('<U4')) -> None

## Built-in Methods

There are lots of built-in ways to generate Arrays

### Reshape function

In [71]:
arr1

array([[[1, 2, 3],
        [4, 5, 6]],

       [[4, 5, 4],
        [9, 0, 9]]])

In [72]:
arr1.shape

(2, 2, 3)

In [76]:
arr1.reshape((3,2,2)) 

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [4, 5]],

       [[4, 9],
        [0, 9]]])

In [77]:
arr2=arr1.reshape((4,3))  # reshape function takes the new shape as its argument

In [78]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [4, 5, 4],
       [9, 0, 9]])

In [81]:
arr2 = arr2.reshape(-1)

In [82]:
arr2

array([1, 2, 3, 4, 5, 6, 4, 5, 4, 9, 0, 9])

### arange

Return evenly spaced values within a given interval.

In [112]:
np.arange(15) # end; default start at 0

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [113]:
np.arange(2,15) # start, end and step

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [85]:
np.arange(0,10,3) # start end and step

array([0, 3, 6, 9])

### zeros and ones

Generate arrays of zeros or ones

In [ ]:
import numpy as np

In [95]:
a = np.zeros(3) # Generates array in 1 dimension with all elements 0

In [93]:
a1 = a = np.zeros(3,dtype="int")

In [96]:
print(a)
print(a1)

[0. 0. 0.]
[0 0 0]


In [88]:
a.dtype

dtype('float64')

In [97]:
np.zeros((2,5,5))  # Generates array in 2 diemnsions with all elements 0

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [99]:
np.ones(3,dtype='int') # Generates array of 1 dimension where all elements are 1

array([1, 1, 1])

In [100]:
b = np.ones((1,2,3)) # Generates array of 3 dimensions where all elements are 1

In [101]:
b.shape

(1, 2, 3)

In [102]:
b

array([[[1., 1., 1.],
        [1., 1., 1.]]])

In [103]:
b[0][0][0]

1.0

### linspace
Return evenly spaced numbers over a specified interval.

In [87]:
import numpy as np

In [104]:
np.linspace(1,25)  # default 50 observations
# both the start and end are included in the array

array([ 1.        ,  1.48979592,  1.97959184,  2.46938776,  2.95918367,
        3.44897959,  3.93877551,  4.42857143,  4.91836735,  5.40816327,
        5.89795918,  6.3877551 ,  6.87755102,  7.36734694,  7.85714286,
        8.34693878,  8.83673469,  9.32653061,  9.81632653, 10.30612245,
       10.79591837, 11.28571429, 11.7755102 , 12.26530612, 12.75510204,
       13.24489796, 13.73469388, 14.2244898 , 14.71428571, 15.20408163,
       15.69387755, 16.18367347, 16.67346939, 17.16326531, 17.65306122,
       18.14285714, 18.63265306, 19.12244898, 19.6122449 , 20.10204082,
       20.59183673, 21.08163265, 21.57142857, 22.06122449, 22.55102041,
       23.04081633, 23.53061224, 24.02040816, 24.51020408, 25.        ])

In [107]:
np.linspace(5,25,10,retstep=False,dtype="int")

array([ 5,  7,  9, 11, 13, 16, 18, 20, 22, 25])

In [139]:
np.linspace(5,25,10,retstep=True)  # equally spaced 10 values

(array([ 5.        ,  7.22222222,  9.44444444, 11.66666667, 13.88888889,
        16.11111111, 18.33333333, 20.55555556, 22.77777778, 25.        ]),
 2.2222222222222223)

In [ ]:
# retstep ~ return step computed by linspace

In [143]:
np.linspace(0,25, retstep=True) # Start # end (Here end is included) and default elements are 50

(array([ 0.        ,  0.51020408,  1.02040816,  1.53061224,  2.04081633,
         2.55102041,  3.06122449,  3.57142857,  4.08163265,  4.59183673,
         5.10204082,  5.6122449 ,  6.12244898,  6.63265306,  7.14285714,
         7.65306122,  8.16326531,  8.67346939,  9.18367347,  9.69387755,
        10.20408163, 10.71428571, 11.2244898 , 11.73469388, 12.24489796,
        12.75510204, 13.26530612, 13.7755102 , 14.28571429, 14.79591837,
        15.30612245, 15.81632653, 16.32653061, 16.83673469, 17.34693878,
        17.85714286, 18.36734694, 18.87755102, 19.3877551 , 19.89795918,
        20.40816327, 20.91836735, 21.42857143, 21.93877551, 22.44897959,
        22.95918367, 23.46938776, 23.97959184, 24.48979592, 25.        ]),
 0.5102040816326531)

In [108]:
np.linspace(50,200,10) # default retstep=False

array([ 50.        ,  66.66666667,  83.33333333, 100.        ,
       116.66666667, 133.33333333, 150.        , 166.66666667,
       183.33333333, 200.        ])

In [109]:
np.linspace(50,200,10,retstep=True)

(array([ 50.        ,  66.66666667,  83.33333333, 100.        ,
        116.66666667, 133.33333333, 150.        , 166.66666667,
        183.33333333, 200.        ]),
 16.666666666666668)

### eye

Creates an identity matrix

In [113]:
np.eye(100)   # generates 2d array of (5,5)

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [ ]:
# Create an eye from a zeros array

### Broadcasting in an array

In [114]:
big_one = np.ones((3,4))
print(big_one)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [115]:
big_one.dtype

dtype('float64')

In [117]:
big_one * 3

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

#### The ability to access each and every element of an array is known as Broadcasting.

In [119]:
bigger_one=big_one*6 -2
bigger_one

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [122]:
bigger=np.array(big_one, dtype=int)
print(bigger)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [120]:
bigger=np.array(big_one*3 - 0.4)
print(bigger)

[[2.6 2.6 2.6 2.6]
 [2.6 2.6 2.6 2.6]
 [2.6 2.6 2.6 2.6]]


In [123]:
bigger=np.array(big_one*3 - 0.4, dtype='int')
print(bigger)

[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


In [162]:
bigger.dtype

dtype('int32')

In [163]:
type(bigger)

numpy.ndarray

In [164]:
bigger.shape

(3, 4)

In [124]:
bigger

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [166]:
bigger/bigger

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [125]:
1/arr1[1:]

C:\Users\OMEN\AppData\Local\Temp\ipykernel_74816\1811120542.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr1[1:]


array([[[0.25      , 0.2       , 0.25      ],
        [0.11111111,        inf, 0.11111111]]])

In [126]:
arr1 = np.arange(20)

In [127]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [169]:
arr1 = np.arange(20)
1/arr1

C:\Users\OMEN\AppData\Local\Temp\ipykernel_81840\3219800275.py:2: RuntimeWarning: divide by zero encountered in divide
  1/arr1


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       , 0.09090909, 0.08333333, 0.07692308, 0.07142857,
       0.06666667, 0.0625    , 0.05882353, 0.05555556, 0.05263158])

In [128]:
arr=np.arange(4)

In [129]:
arr

array([0, 1, 2, 3])

In [130]:
arr + arr

array([0, 2, 4, 6])

In [173]:
arr

array([0, 1, 2, 3])

In [131]:
arr  ** arr

array([ 1,  1,  4, 27])

In [175]:
2 ** 3

8

### Use of Copy function

In [132]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [133]:
arr2 = arr1 # not recommended
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [134]:
arr1[1]=100

In [135]:
arr1

array([  0, 100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

In [136]:
arr2

array([  0, 100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

In [185]:
arr3

array([  0, 100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

In [139]:
arr1[1]=500

In [141]:
arr3 = arr1.copy() # generate a copy / creates a backup

In [144]:
arr3

array([  0, 500,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

In [145]:
arr3[10:] = 100
arr3

array([  0, 500,   2,   3,   4,   5,   6,   7,   8,   9, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100])

In [146]:

arr1  # copy function retains the original. copy creates a backup array.

array([  0, 500,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

## Random number generation

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [190]:
import numpy as np

In [165]:
np.random.rand()

0.08464027421154541

In [167]:
np.random.rand(100000) # rand gives values between 0 and 1

array([0.14007007, 0.92799276, 0.15021557, ..., 0.04759148, 0.47933165,
       0.33473656])

In [194]:
np.random.rand(5,2)

array([[0.24384372, 0.91457111],
       [0.72613104, 0.45008657],
       [0.19755165, 0.30181611],
       [0.72624822, 0.59754148],
       [0.53361133, 0.61926374]])

In [168]:
# Creating array from uniform distribution
new_arr=np.random.rand(5,3)
# 2 dimensional array of shape (5,3)

In [169]:
new_arr

array([[0.66112614, 0.81963481, 0.99775328],
       [0.39760623, 0.55489131, 0.28067849],
       [0.97918832, 0.84369134, 0.22221649],
       [0.44697941, 0.24362575, 0.40701654],
       [0.01310955, 0.02493915, 0.70079615]])

In [171]:
np.random.rand(2,3,3)

array([[[0.41808788, 0.91573951, 0.2305908 ],
        [0.06835085, 0.48298279, 0.32046333],
        [0.34358834, 0.3728208 , 0.28163779]],

       [[0.83581088, 0.67923427, 0.66032991],
        [0.30993324, 0.67105195, 0.16691873],
        [0.30261918, 0.45007021, 0.98050288]]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [ ]:
# For randn, random numbbers generated will be in approximately -3 to +3 range.

In [184]:
arr1=np.random.randn(10000000)  # 50 observations from std normal distribution
arr1

array([-0.43295804,  1.13715155,  1.13768842, ...,  1.27450885,
       -0.91216501, -0.54184664])

In [185]:
np.mean(arr1)

0.00017770073329300727

In [186]:
np.median(arr1)

0.0003704352344425781

In [187]:
np.std(arr1)

0.9999457077613284

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [234]:
np.random.randint(1,1000000)
# third argument is no. of values. default =1 value

976764

In [236]:
np.random.randint(1,100,100000000)

array([19, 19, 99, ..., 34, 43, 86])

In [237]:
np.random.randint(40,60,50) # generating 50 values between

array([46, 45, 59, 56, 43, 40, 57, 48, 58, 46, 59, 45, 52, 46, 42, 52, 50,
       48, 47, 47, 57, 40, 41, 56, 42, 49, 56, 59, 59, 42, 47, 49, 55, 56,
       45, 44, 44, 52, 56, 43, 45, 54, 49, 45, 50, 42, 57, 52, 58, 55])

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [248]:
arr = np.arange(20)
ranarr = np.random.randint(0,100,10)

In [297]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [249]:
ranarr

array([82, 16,  5, 35, 37, 71, 86, 44, 33, 66])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [238]:
arr2=np.random.randint(1,100,20)

In [239]:
arr2

array([38, 61,  1, 89, 38, 26, 94, 45, 11, 17, 71, 50, 86,  3, 40, 41, 93,
       19, 23, 89])

In [240]:
arr2.max()

94

In [241]:
arr2.min()

1

In [242]:
arr2.argmax()


6

In [243]:
arr2.argmin()

2

In [245]:
arr

array([0, 1, 2, 3])

In [244]:
arr.max()

3

In [250]:
ranarr

array([82, 16,  5, 35, 37, 71, 86, 44, 33, 66])

In [251]:
ranarr.argmax() ## Index location of highest element

6

In [252]:
ranarr.min() # Gives the lowest element of array

5

In [253]:
ranarr.argmin() # Index location of lowest element

2

In [258]:
ran2=ranarr.reshape(2,1,5)

In [259]:
ran2

array([[[82, 16,  5, 35, 37]],

       [[71, 86, 44, 33, 66]]])

In [260]:
ran2.argmax()

6

In [257]:
ran2.max()

86

# Happy Learning!