# NumPy Indexing and Selection

Here we will discuss how to select elements or groups of elements from an array.

In [1]:
import numpy as np

In [2]:
#Creating sample array
arr=np.arange(0,21)

In [3]:
#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [4]:
#Creating sample array
arr=np.arange(10,100,5)
arr

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [5]:
len(arr)

18

In [6]:
arr.size

18

In [7]:
arr

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [8]:
arr[17]

95

In [9]:
arr[-1]

95

In [10]:
#Get a value at an index
arr[9]

55

In [11]:
arr

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [12]:
arr[1:11]

array([15, 20, 25, 30, 35, 40, 45, 50, 55, 60])

In [13]:
#Get values in a range
arr[1:11:2]

array([15, 25, 35, 45, 55])

### Filtering

In [14]:
import numpy as np

In [15]:
# Filtering condition

arr=np.array([1,2,1010,4,108,18,71,610,71])
arr

array([   1,    2, 1010,    4,  108,   18,   71,  610,   71])

In [16]:
arr<100

array([ True,  True, False,  True, False,  True,  True, False,  True])

In [17]:
arr2=np.array([True,False,False,True])

In [18]:
arr2[2]

False

In [19]:
np.where(arr2)

(array([0, 3], dtype=int64),)

In [20]:
arr

array([   1,    2, 1010,    4,  108,   18,   71,  610,   71])

In [21]:
np.where(arr)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int64),)

In [22]:
arr

array([   1,    2, 1010,    4,  108,   18,   71,  610,   71])

In [23]:
arr[5]

18

In [24]:
arr[2]

1010

In [25]:
arr

array([   1,    2, 1010,    4,  108,   18,   71,  610,   71])

In [26]:
np.where(arr<100)# where function outputs index location of values
# meeting the condition

(array([0, 1, 3, 5, 6, 8], dtype=int64),)

In [27]:
np.where(arr>100)

(array([2, 4, 7], dtype=int64),)

In [28]:
arr[np.where(arr>100)]

array([1010,  108,  610])

In [29]:
arr[np.where(arr>100)]=10

In [30]:
arr

array([ 1,  2, 10,  4, 10, 18, 71, 10, 71])

In [31]:
np.where(arr<100)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int64),)

In [32]:
np.where(arr==71)

(array([6, 8], dtype=int64),)

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. It is recommended to use the comma notation for clarity.

In [33]:
import numpy as np

In [34]:
11+12

23

In [35]:
# a,b=int(input("Enter a number ")),int(input("Enter a number"))
# print("sum of a and b is ",(a+b))

In [36]:
arr_2d = np.array((
    [1,2,3],
    [12,15,18],
    [64,96,128]))

#Show
arr_2d

array([[  1,   2,   3],
       [ 12,  15,  18],
       [ 64,  96, 128]])

In [37]:
arr_2d = np.array(([1,2,3],[12,15,18],[64,96,128]))

#Show
arr_2d

array([[  1,   2,   3],
       [ 12,  15,  18],
       [ 64,  96, 128]])

In [38]:
arr_2d[1][1]

15

In [39]:
arr_2d[:,1]

array([ 2, 15, 96])

In [40]:
arr_2d[2,:]

array([ 64,  96, 128])

In [41]:
l1=[1,2,3,4,5]

In [42]:
l1[:3]

[1, 2, 3]

In [43]:
arr_2d

array([[  1,   2,   3],
       [ 12,  15,  18],
       [ 64,  96, 128]])

In [44]:
arr_2d[:2,:2]

array([[ 1,  2],
       [12, 15]])

In [45]:
np.arange(27)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [46]:
arr3=np.arange(27).reshape(3,3,3)

In [47]:
arr3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [48]:
arr_2d

array([[  1,   2,   3],
       [ 12,  15,  18],
       [ 64,  96, 128]])

In [49]:
arr_2d[0:2,:]

array([[ 1,  2,  3],
       [12, 15, 18]])

In [50]:
arr_2d[:2,1]

array([ 2, 15])

In [51]:
arr_2d

array([[  1,   2,   3],
       [ 12,  15,  18],
       [ 64,  96, 128]])

In [52]:
arr_2d[:1,:2]

array([[1, 2]])

In [53]:
arr_2d.shape

(3, 3)

In [54]:
arr4=np.arange(15).reshape(3,5)

In [55]:
arr4

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [56]:
arr4[1:,1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [58]:
arr_2d

array([[  1,   2,   3],
       [ 12,  15,  18],
       [ 64,  96, 128]])

In [59]:
arr_2d[1]  # Indexing 2nd row

array([12, 15, 18])

In [60]:
arr_2d[:,2] # Indexing 3rd column

array([  3,  18, 128])

In [61]:
arr_2d[1:,1:]

array([[ 15,  18],
       [ 96, 128]])

In [62]:
arr_2d[1,1]

15

In [63]:
arr_2d[0:2][0:2]

array([[ 1,  2,  3],
       [12, 15, 18]])

In [64]:
# Indexing column
arr_2d[:,2]

array([  3,  18, 128])

In [65]:
arr5=np.arange(20).reshape(5,4)

In [66]:
arr5

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [67]:
arr5[1:4,1:3]

array([[ 5,  6],
       [ 9, 10],
       [13, 14]])

In [68]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[ 2,  3],
       [15, 18]])

### Fancy Indexing

Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array:

In [72]:
arr1=np.ones((10,10))
arr1.shape

(10, 10)

In [75]:
arr1

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [71]:
len(arr1)

10

In [76]:
for i in range(len(arr1)):
  arr1[i]=i

In [77]:
arr1

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [78]:
arr3=np.arange(27).reshape(3,3,3)

In [79]:
arr3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [80]:
#Set up matrix
arr2d = np.zeros(arr1.shape)  # taking shape from an existing array

In [81]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [82]:
arr2d.shape

(10, 10)

In [85]:
t2 = arr2d.shape

In [86]:
t2

(10, 10)

In [87]:
t2[0]

10

In [89]:
arr2d.shape[1]

10

In [83]:
t1 = (1,2)

In [84]:
t1[1]

2

In [90]:
no_of_rows=arr2d.shape[0]  # indexing the shape tuple

In [91]:
#Set up array

for i in range(no_of_rows):
    arr2d[i] = i

arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

Fancy indexing allows the following

In [92]:
arr2d[[6,3,8]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [94]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [93]:
arr2d[:,[2,4,6,8]]

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.],
       [8., 8., 8., 8.],
       [9., 9., 9., 9.]])

In [95]:
#Allows in any order
arr2d[[6,4,2,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

## Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [96]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [97]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [98]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [99]:
arr2d[:,0]<4

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

# Happy Learning!