1. Improve the parameter grid for decision tree and observe improvement.
2. Perform hyperparameter tunning for randomForest Model and observe the result
3. tryout a boosting model as well

In [1]:
import pandas as pd
import numpy as np


In [2]:
df = pd.read_csv('1_Churn_Modelling.csv')

In [3]:
df

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [4]:
df.drop(['RowNumber','CustomerId','Surname'], axis = 1, inplace=True)

In [5]:
df

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France  Female   42       2       0.00              1   
1             608     Spain  Female   41       1   83807.86              1   
2             502    France  Female   42       8  159660.80              3   
3             699    France  Female   39       1       0.00              2   
4             850     Spain  Female   43       2  125510.82              1   
...           ...       ...     ...  ...     ...        ...            ...   
9995          771    France    Male   39       5       0.00              2   
9996          516    France    Male   35      10   57369.61              1   
9997          709    France  Female   36       7       0.00              1   
9998          772   Germany    Male   42       3   75075.31              2   
9999          792    France  Female   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0             1               1        101348.88       1  
1             0               1        112542.58       0  
2             1               0        113931.57       1  
3             0               0         93826.63       0  
4             1               1         79084.10       0  
...         ...             ...              ...     ...  
9995          1               0         96270.64       0  
9996          1               1        101699.77       0  
9997          0               1         42085.58       1  
9998          1               0         92888.52       1  
9999          1               0         38190.78       0  

[10000 rows x 11 columns]

In [6]:
df.isnull().sum()

CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [7]:
df.describe()

CreditScore           Age        Tenure        Balance  NumOfProducts  \
count  10000.000000  10000.000000  10000.000000   10000.000000   10000.000000   
mean     650.528800     38.921800      5.012800   76485.889288       1.530200   
std       96.653299     10.487806      2.892174   62397.405202       0.581654   
min      350.000000     18.000000      0.000000       0.000000       1.000000   
25%      584.000000     32.000000      3.000000       0.000000       1.000000   
50%      652.000000     37.000000      5.000000   97198.540000       1.000000   
75%      718.000000     44.000000      7.000000  127644.240000       2.000000   
max      850.000000     92.000000     10.000000  250898.090000       4.000000   

         HasCrCard  IsActiveMember  EstimatedSalary        Exited  
count  10000.00000    10000.000000     10000.000000  10000.000000  
mean       0.70550        0.515100    100090.239881      0.203700  
std        0.45584        0.499797     57510.492818      0.402769  
min        0.00000        0.000000        11.580000      0.000000  
25%        0.00000        0.000000     51002.110000      0.000000  
50%        1.00000        1.000000    100193.915000      0.000000  
75%        1.00000        1.000000    149388.247500      0.000000  
max        1.00000        1.000000    199992.480000      1.000000

In [8]:
df['Gender'].value_counts()

Gender
Male      5457
Female    4543
Name: count, dtype: int64

In [9]:
df['Geography'].value_counts()

Geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64

In [10]:
from sklearn.tree import DecisionTreeClassifier

In [11]:
dt_classifier = DecisionTreeClassifier(random_state=42)
dt_classifier

DecisionTreeClassifier(random_state=42)

In [12]:
df.select_dtypes(include = ['int64','float64']).columns

Index(['CreditScore', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [13]:
categorical_col = df.select_dtypes(include = ['object','bool']).columns

In [14]:
categorical_col

Index(['Geography', 'Gender'], dtype='object')

In [15]:
hot_encode_col = pd.get_dummies(df, columns = categorical_col, drop_first = True)

In [16]:
hot_encode_col

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0             619   42       2       0.00              1          1   
1             608   41       1   83807.86              1          0   
2             502   42       8  159660.80              3          1   
3             699   39       1       0.00              2          0   
4             850   43       2  125510.82              1          1   
...           ...  ...     ...        ...            ...        ...   
9995          771   39       5       0.00              2          1   
9996          516   35      10   57369.61              1          1   
9997          709   36       7       0.00              1          0   
9998          772   42       3   75075.31              2          1   
9999          792   28       4  130142.79              1          1   

      IsActiveMember  EstimatedSalary  Exited  Geography_Germany  \
0                  1        101348.88       1              False   
1                  1        112542.58       0              False   
2                  0        113931.57       1              False   
3                  0         93826.63       0              False   
4                  1         79084.10       0              False   
...              ...              ...     ...                ...   
9995               0         96270.64       0              False   
9996               1        101699.77       0              False   
9997               1         42085.58       1              False   
9998               0         92888.52       1               True   
9999               0         38190.78       0              False   

      Geography_Spain  Gender_Male  
0               False        False  
1                True        False  
2               False        False  
3               False        False  
4                True        False  
...               ...          ...  
9995            False         True  
9996            False         True  
9997            False        False  
9998            False         True  
9999            False        False  

[10000 rows x 12 columns]

x = features all columns except he target

y = only target variable

In [17]:
x = hot_encode_col.drop(['Exited'], axis = 1)
y = hot_encode_col.Exited

In [18]:
x

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0             619   42       2       0.00              1          1   
1             608   41       1   83807.86              1          0   
2             502   42       8  159660.80              3          1   
3             699   39       1       0.00              2          0   
4             850   43       2  125510.82              1          1   
...           ...  ...     ...        ...            ...        ...   
9995          771   39       5       0.00              2          1   
9996          516   35      10   57369.61              1          1   
9997          709   36       7       0.00              1          0   
9998          772   42       3   75075.31              2          1   
9999          792   28       4  130142.79              1          1   

      IsActiveMember  EstimatedSalary  Geography_Germany  Geography_Spain  \
0                  1        101348.88              False            False   
1                  1        112542.58              False             True   
2                  0        113931.57              False            False   
3                  0         93826.63              False            False   
4                  1         79084.10              False             True   
...              ...              ...                ...              ...   
9995               0         96270.64              False            False   
9996               1        101699.77              False            False   
9997               1         42085.58              False            False   
9998               0         92888.52               True            False   
9999               0         38190.78              False            False   

      Gender_Male  
0           False  
1           False  
2           False  
3           False  
4           False  
...           ...  
9995         True  
9996         True  
9997        False  
9998         True  
9999        False  

[10000 rows x 11 columns]

In [19]:
y

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

Splitting data into training and testing sets

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
# split data : 80% for training, 20% for testing
# random states ensure reproducibility of data split

In [22]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.2 , random_state=42)

In [23]:
print(x_train)
print(x_test)
print(y_train)
print(y_test)

      CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
9254          686   32       6       0.00              2          1   
1561          632   42       4  119624.60              2          1   
1670          559   24       3  114739.92              1          1   
6087          561   27       9  135637.00              1          1   
6669          517   56       9  142147.32              1          0   
...           ...  ...     ...        ...            ...        ...   
5734          768   54       8   69712.74              1          1   
5191          682   58       1       0.00              1          1   
5390          735   38       1       0.00              3          0   
860           667   43       8  190227.46              1          1   
7270          697   51       1  147910.30              1          1   

      IsActiveMember  EstimatedSalary  Geography_Germany  Geography_Spain  \
9254               1        179093.26              False            Fa

#### Model Building and Hyperparameter tunning

In [24]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score, classification_report

In [25]:
dt_classifier  = DecisionTreeClassifier(random_state = 42)

In [26]:
dt_classifier

DecisionTreeClassifier(random_state=42)

In [27]:
dt_classifier.fit(x_train, y_train)

DecisionTreeClassifier(random_state=42)

In [28]:
y_train_pred = dt_classifier.predict(x_train)

In [29]:
y_train_pred

array([0, 0, 1, ..., 1, 1, 0])

In [30]:
accuracy_score(y_train_pred, y_train)

1.0

In [31]:
y_test_predic = dt_classifier.predict(x_test)
y_test_predic

array([0, 0, 0, ..., 1, 0, 1])

In [110]:
accuracy_initial = accuracy_score(y_test_predic,y_test)
accuracy_initial

0.7805

In [100]:

report = classification_report(y_test, y_test_predic)
print(report)

              precision    recall  f1-score   support

           0       0.88      0.85      0.86      1607
           1       0.45      0.51      0.48       393

    accuracy                           0.78      2000
   macro avg       0.66      0.68      0.67      2000
weighted avg       0.79      0.78      0.79      2000



tunning decision tree

In [33]:
param_drid_dt = {
    'criterion' : ['gini','entropy'],
    'splitter' : ['best','random'],
    'max_depth' : [None, 5,10,15,20],
    'min_samples_split' : [2,5,10],
    'min_samples_leaf' : [1,2,4],
    'max_features' : [None, 'sqrt','log2']
}

In [34]:
grid_search_dt = GridSearchCV(
    estimator = dt_classifier,
    param_grid=param_drid_dt,
    cv =5,
    scoring='accuracy',
    verbose=1
)

In [35]:
grid_search_dt.fit(x_train, y_train)

Fitting 5 folds for each of 540 candidates, totalling 2700 fits


GridSearchCV(cv=5, estimator=DecisionTreeClassifier(random_state=42),
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [None, 5, 10, 15, 20],
                         'max_features': [None, 'sqrt', 'log2'],
                         'min_samples_leaf': [1, 2, 4],
                         'min_samples_split': [2, 5, 10],
                         'splitter': ['best', 'random']},
             scoring='accuracy', verbose=1)

In [36]:
grid_search_dt.fit(x_train, y_train)

Fitting 5 folds for each of 540 candidates, totalling 2700 fits


GridSearchCV(cv=5, estimator=DecisionTreeClassifier(random_state=42),
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [None, 5, 10, 15, 20],
                         'max_features': [None, 'sqrt', 'log2'],
                         'min_samples_leaf': [1, 2, 4],
                         'min_samples_split': [2, 5, 10],
                         'splitter': ['best', 'random']},
             scoring='accuracy', verbose=1)

In [37]:
grid_search_dt.best_score_

0.8533750000000001

In [38]:
grid_search_dt.best_params_

{'criterion': 'entropy',
 'max_depth': 5,
 'max_features': None,
 'min_samples_leaf': 2,
 'min_samples_split': 2,
 'splitter': 'best'}

In [39]:
best_dt_model = grid_search_dt.best_estimator_

In [40]:
y_pred_dt = best_dt_model.predict(x_test)
y_pred_dt

array([0, 0, 0, ..., 1, 0, 0])

In [41]:
test_accuracy = accuracy_score(y_pred_dt, y_test)
test_accuracy

0.857

### Random FOrest hyperparameter tunning

In [42]:
from sklearn.ensemble import RandomForestClassifier

In [43]:
rf_classifier = RandomForestClassifier(random_state = 42)

In [44]:
rf_classifier.fit(x_train, y_train)

RandomForestClassifier(random_state=42)

In [46]:
rf_y_pred = rf_classifier.predict(x_test)
rf_y_pred

array([0, 0, 0, ..., 1, 0, 0])

In [47]:
rf_accuracy = accuracy_score(y_test, rf_y_pred)
rf_accuracy

0.8665

In [48]:
rf_report = classification_report(y_test, rf_y_pred)

In [65]:
print(rf_report)

              precision    recall  f1-score   support

           0       0.88      0.96      0.92      1607
           1       0.76      0.47      0.58       393

    accuracy                           0.87      2000
   macro avg       0.82      0.72      0.75      2000
weighted avg       0.86      0.87      0.85      2000



In [50]:
param_grid_rf = {
    'max_depth': [None, 10, 20],
    'min_samples_split': [2, 5],
    'min_samples_leaf': [1, 2]
}

In [51]:
param_grid_rf

{'max_depth': [None, 10, 20],
 'min_samples_split': [2, 5],
 'min_samples_leaf': [1, 2]}

In [52]:
grid_search_rf = GridSearchCV(
    estimator = RandomForestClassifier(random_state=42),
    param_grid = param_grid_rf,
    cv=5,
    scoring='accuracy',
    n_jobs = -1, #number of core utilize
    verbose = 1
)


In [53]:
grid_search_rf.fit(x_train, y_train)

Fitting 5 folds for each of 12 candidates, totalling 60 fits


GridSearchCV(cv=5, estimator=RandomForestClassifier(random_state=42), n_jobs=-1,
             param_grid={'max_depth': [None, 10, 20],
                         'min_samples_leaf': [1, 2],
                         'min_samples_split': [2, 5]},
             scoring='accuracy', verbose=1)

In [55]:
best_param_rf = grid_search_rf.best_params_
best_param_rf

{'max_depth': 20, 'min_samples_leaf': 2, 'min_samples_split': 2}

In [56]:
best_score_rf = grid_search_rf.best_score_
best_score_rf

0.86525

In [57]:
# best estimator
best_rf_classifier = grid_search_rf.best_estimator_
best_rf_classifier

RandomForestClassifier(max_depth=20, min_samples_leaf=2, random_state=42)

In [58]:
# make prediction with the best model
y_pred_tunned_rf = best_rf_classifier.predict(x_test)

In [59]:
y_pred_tunned_rf

array([0, 0, 0, ..., 1, 0, 0])

In [61]:
accuracy_tunned_rf = accuracy_score(y_test, y_pred_tunned_rf)
accuracy_tunned_rf

0.8705

In [64]:
report_tunned_rf = classification_report(y_test, y_pred_tunned_rf)
print(report_tunned_rf)

              precision    recall  f1-score   support

           0       0.88      0.97      0.92      1607
           1       0.77      0.48      0.59       393

    accuracy                           0.87      2000
   macro avg       0.83      0.72      0.76      2000
weighted avg       0.86      0.87      0.86      2000



#### Boosting model

In [67]:
from sklearn.ensemble import GradientBoostingClassifier

In [68]:
boost_classifier = GradientBoostingClassifier(random_state = 42)

In [69]:
boost_classifier.fit(x_train, y_train)

GradientBoostingClassifier(random_state=42)

In [70]:
y_pred_boost = boost_classifier.predict(x_test)

In [73]:
y_pred_boost

array([0, 0, 0, ..., 1, 0, 0])

In [74]:
boost_accuracy = accuracy_score(y_test, y_pred_boost)
print(boost_accuracy)

0.8675


In [75]:
boost_report = classification_report(y_test, y_pred_boost)

In [77]:
print(boost_report)

              precision    recall  f1-score   support

           0       0.88      0.96      0.92      1607
           1       0.75      0.49      0.59       393

    accuracy                           0.87      2000
   macro avg       0.82      0.72      0.76      2000
weighted avg       0.86      0.87      0.86      2000



In [79]:
param_grid_boost = {
    'n_estimators': [50, 100, 200], # Number of boosting stages
    'learning_rate': [0.01, 0.1, 0.2], # Step size shrinkage to prevent overfitting
    'max_depth': [3, 5, 7], # Maximum depth of the individual regression estimators
    'subsample': [0.8, 1.0], # Fraction of samples to be used for fitting the individual base learners
    'min_samples_split': [2, 5]}

In [86]:
grid_search_boost = GridSearchCV(
    estimator=GradientBoostingClassifier(random_state=42),
    param_grid=param_grid_boost,
    cv=5,
    scoring='accuracy',
    n_jobs=-1,
    verbose=1
)

In [87]:
grid_search_boost.fit(x_train, y_train)

Fitting 5 folds for each of 108 candidates, totalling 540 fits


GridSearchCV(cv=5, estimator=GradientBoostingClassifier(random_state=42),
             n_jobs=-1,
             param_grid={'learning_rate': [0.01, 0.1, 0.2],
                         'max_depth': [3, 5, 7], 'min_samples_split': [2, 5],
                         'n_estimators': [50, 100, 200],
                         'subsample': [0.8, 1.0]},
             scoring='accuracy', verbose=1)

In [89]:
# best parameter
best_param_boost = grid_search_boost.best_params_
print(best_param_boost)

{'learning_rate': 0.1, 'max_depth': 5, 'min_samples_split': 2, 'n_estimators': 50, 'subsample': 0.8}


In [90]:
# best score
best_score_boost = grid_search_boost.best_score_
print(best_score_boost)

0.8637499999999999


In [91]:
# best estimator
best_boost_classifier = grid_search_boost.best_estimator_
print(best_boost_classifier)

GradientBoostingClassifier(max_depth=5, n_estimators=50, random_state=42,
                           subsample=0.8)


In [93]:
# predict with best model
y_pred_tunned_boost = best_boost_classifier.predict(x_test)
print(y_pred_tunned_boost)

[0 0 0 ... 1 0 0]


In [94]:
# accuracy score
accuracy_tunned_boost = accuracy_score(y_test, y_pred_tunned_boost)

print(accuracy_tunned_boost)

0.8635


In [95]:
report_tunned_boost = classification_report(y_test, y_pred_tunned_boost)
print(report_tunned_boost)

              precision    recall  f1-score   support

           0       0.88      0.96      0.92      1607
           1       0.74      0.47      0.58       393

    accuracy                           0.86      2000
   macro avg       0.81      0.72      0.75      2000
weighted avg       0.85      0.86      0.85      2000



<function accuracy_score at 0x7f0800ac96c0>


In [113]:
print('\n --- Overall Model Performance Summary ---')
print(f"Initial Decision tree Accuracy: {accuracy_initial:.4f}")
print(f'Tunned Decision Tree Accuracy: {test_accuracy:.4f} (Impovement : {test_accuracy - accuracy_initial:.4f})')
print("-" * 40)
print(f'Initial Random Forest Accuracy: {rf_accuracy:.4f}')
print(f'Tunned Random Forest Accuracy: {accuracy_tunned_rf:.4f} (Improvement: { accuracy_tunned_rf- rf_accuracy:.4f})')
print("-" * 40)
print(f'Initial Gradient Boost Accuracy: {boost_accuracy:.4f}')
print(f'Tunned Gradient Boosting Accuracy: {accuracy_tunned_boost}(Improvement: {accuracy_tunned_boost - boost_accuracy:.4f})')


 --- Overall Model Performance Summary ---
Initial Decision tree Accuracy: 0.7805
Tunned Decision Tree Accuracy: 0.8570 (Impovement : 0.0765)
----------------------------------------
Initial Random Forest Accuracy: 0.8665
Tunned Random Forest Accuracy: 0.8705 (Improvement: 0.0040)
----------------------------------------
Initial Gradient Boost Accuracy: 0.8675
Tunned Gradient Boosting Accuracy: 0.8635(Improvement: -0.0040)
